version: '3'
services:
  mysql_loja:
    image: mysql:8.3.0
    hostname: mysql_loja
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql


# sudo mysql -h127.0.0.1 -P3306 -uroot -proot
