global:
  scrape_interval:     10s
  evaluation_interval: 10s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - 'prometheus:9090'
         
  - job_name: 'api_dash'
    static_configs:
      - targets:
        - 'api_dashboard:4000'

  - job_name: docker
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
    static_configs:
      - targets: ['172.17.0.1:9323']

# ATENTION WITH job docker;
# IP MAY NOT BE 172.17.0.1 DEPENDS OF ENVIRONMENT
# run ip addr show docker0 to get inet ip (docker0)
# set target with
# set /etc/docker/daemon.json with ip got:
#   {
#     "metrics-addr" : "ip_got:9323",
#     "experimental" : true
#   }
# run systemctl daemon-reload
# run systemctl restart docker